// Martial PC creature minis — now generated by the procedural miniature engine
// ($lib/minis) via the fromRecipe() adapter. Each ModelDef keeps its stable id /
// label / icon / color / category / keywords (pickMiniId, the Figures panel and
// the auto NPC catalog all key off those) and swaps only its `build` for a
// compact recipe: class + species + gear + pose. The engine owns every
// sculptural decision, so these read as one premium product line instead of a
// bag of hand-placed boxes.
//
// EXCEPTION: `mounted-knight` is still hand-built — a rider-on-quadruped-mount
// composite has no representation in the biped recipe system (see
// docs/miniature-generator.md). Everything else is a recipe.
import { C } from './kit.ts';
import type { ModelDef, ModelBuild } from './types.ts';
import { fromRecipe } from './miniRecipe.ts';

// A round shield held on the left arm (mounted-knight only — recipe minis get
// their shields from the gear library). Placed in front of the left hand so the
// arm presses against its back instead of poking through the face.
const shield = (k: Parameters<ModelBuild>[0], color: string | number, bulk = 1) => {
  const x = -0.225 * bulk, z = 0.06 + 0.055 * bulk;
  return k.group(
    k.rot(k.cyl(0.18, 0.18, 0.04, color, x, 0.55, z, 18), Math.PI / 2),
    k.sph(0.045, C.STEEL, x, 0.55, z + 0.03),
  );
};

export const MODELS: ModelDef[] = [
  {
    id: 'warrior-sword-shield', label: 'Warrior', icon: '🗡️', color: '#9aa3ad',
    category: 'PC', creature: true,
    keywords: ['warrior', 'fighter', 'soldier', 'guard', 'swordsman', 'mercenary', 'veteran', 'man-at-arms', 'shield bearer'],
    build: fromRecipe({
      name: 'Warrior', class: 'fighter', species: 'human',
      gear: ['sword', 'round_shield'], poseFamily: 'shield_bash', armorWeight: 'medium',
      materials: { metal: 'brushed_steel', cloth: 'charcoal' },
    }),
  },
  {
    id: 'greatsword-warrior', label: 'Greatsword Warrior', icon: '⚔️', color: '#b7bdc4',
    category: 'PC', creature: true,
    keywords: ['greatsword', 'two-handed', 'claymore', 'zweihander'],
    build: fromRecipe({
      name: 'Greatsword Warrior', class: 'fighter', species: 'human', bodyType: 'burly',
      gear: ['greatsword'], poseFamily: 'two_handed_weapon_pose', armorWeight: 'heavy',
      materials: { metal: 'dark_iron', metal2: 'brushed_steel' },
    }),
  },
  {
    id: 'dual-wielder', label: 'Dual Wielder', icon: '🗡️', color: '#c8ccd2',
    category: 'PC', creature: true,
    keywords: ['dual', 'dual-wield', 'two weapons'],
    build: fromRecipe({
      name: 'Dual Wielder', class: 'fighter', species: 'human', bodyType: 'lean',
      gear: ['dual_swords'], poseFamily: 'sword_lunge', armorWeight: 'light',
      materials: { leather: 'black_leather', metal: 'brushed_steel' },
    }),
  },
  {
    id: 'spearman', label: 'Spearman', icon: '🔱', color: '#8a6f4a',
    category: 'PC', creature: true,
    keywords: ['spear', 'lancer', 'pikeman', 'polearm fighter'],
    build: fromRecipe({
      name: 'Spearman', class: 'fighter', species: 'human',
      gear: ['spear', 'round_shield'], poseFamily: 'shield_bash', armorWeight: 'light',
      materials: { cloth: 'warm_grey', leather: 'tan_leather' },
    }),
  },
  {
    id: 'axeman', label: 'Axeman', icon: '🪓', color: '#6e4a2c',
    category: 'PC', creature: true,
    keywords: ['axe', 'axeman'],
    build: fromRecipe({
      name: 'Axeman', class: 'fighter', species: 'human',
      gear: ['battleaxe', 'round_shield'], poseFamily: 'shield_bash', armorWeight: 'medium',
      materials: { leather: 'dark_brown', metal: 'dark_iron' },
    }),
  },
  {
    id: 'hammer-warrior', label: 'Hammer Warrior', icon: '🔨', color: '#55585e',
    category: 'PC', creature: true,
    keywords: ['hammer', 'maul', 'warhammer'],
    build: fromRecipe({
      name: 'Hammer Warrior', class: 'fighter', species: 'human', bodyType: 'burly',
      gear: ['warhammer'], poseFamily: 'smite_strike', armorWeight: 'heavy',
      materials: { metal: 'dark_iron', metal2: 'brushed_steel' },
    }),
  },
  {
    id: 'knight', label: 'Knight', icon: '🛡️', color: '#b7bdc4',
    category: 'PC', creature: true,
    keywords: ['knight', 'paladin', 'armored', 'cavalier', 'evil knight'],
    build: fromRecipe({
      name: 'Knight', class: 'paladin', species: 'human',
      gear: ['sword', 'heater_shield', 'tabard'], poseFamily: 'shield_bash', armorWeight: 'heavy',
      materials: { metal: 'brushed_steel', metal2: 'gold', cloth2: 'wine_red' },
    }),
  },
  {
    id: 'barbarian', label: 'Barbarian', icon: '🪓', color: '#8a5a3a',
    category: 'PC', creature: true,
    keywords: ['barbarian', 'berserker', 'raider', 'tribal'],
    build: fromRecipe({
      name: 'Barbarian', class: 'barbarian', species: 'human', bodyType: 'massive',
      gear: ['great_axe', 'fur_mantle'], poseFamily: 'axe_roar', armorWeight: 'none',
      materials: { skin: 'tan_skin', fur: 'brown_fur', leather: 'dark_brown' },
    }),
  },
  {
    id: 'monk', label: 'Monk', icon: '🥋', color: '#8a6f4a',
    category: 'PC', creature: true,
    keywords: ['monk', 'unarmed', 'brawler', 'martial artist'],
    build: fromRecipe({
      name: 'Monk', class: 'monk', species: 'human',
      gear: ['monk_staff', 'sash'], poseFamily: 'staff_sweep', armorWeight: 'none',
      materials: { cloth: 'ochre', cloth2: 'wine_red' },
    }),
  },
  {
    id: 'archer', label: 'Archer', icon: '🏹', color: '#4a7340',
    category: 'PC', creature: true,
    keywords: ['archer', 'bowman'],
    build: fromRecipe({
      name: 'Archer', class: 'ranger', species: 'human',
      gear: ['bow', 'quiver', 'hooded_cloak'], poseFamily: 'bow_drawn', armorWeight: 'light',
      classMarkers: ['hood_up'], materials: { cloth: 'deep_green', leather: 'dark_brown' },
    }),
  },
  {
    id: 'crossbowman', label: 'Crossbowman', icon: '🏹', color: '#6e4a2c',
    category: 'PC', creature: true,
    keywords: ['crossbow', 'crossbowman'],
    build: fromRecipe({
      name: 'Crossbowman', class: 'fighter', species: 'human',
      gear: ['crossbow'], poseFamily: 'two_handed_weapon_pose', armorWeight: 'light',
      materials: { leather: 'tan_leather', cloth: 'warm_grey' },
    }),
  },
  {
    id: 'polearm-fighter', label: 'Polearm Fighter', icon: '🔱', color: '#9aa3ad',
    category: 'PC', creature: true,
    keywords: ['halberd', 'glaive', 'pike', 'polearm'],
    build: fromRecipe({
      name: 'Polearm Fighter', class: 'fighter', species: 'human',
      gear: ['halberd'], poseFamily: 'two_handed_weapon_pose', armorWeight: 'medium',
      materials: { metal: 'brushed_steel', cloth: 'charcoal' },
    }),
  },
  {
    id: 'ranger', label: 'Ranger', icon: '🏹', color: '#3f6b3a',
    category: 'PC', creature: true,
    keywords: ['ranger', 'scout', 'hunter'],
    build: fromRecipe({
      name: 'Ranger', class: 'ranger', species: 'human',
      gear: ['sword', 'cloak', 'quiver'], poseFamily: 'scouting_pose', armorWeight: 'light',
      classMarkers: ['hood_up', 'wilderness_gear'], materials: { cloth: 'forest_green', leather: 'dark_brown' },
    }),
  },
  {
    id: 'mounted-knight', label: 'Mounted Knight', icon: '🐴', color: '#b7bdc4',
    category: 'PC', creature: true, size: 2,
    keywords: ['mounted', 'cavalry', 'rider'],
    // Hand-built: a rider-on-mount composite is outside the biped recipe engine.
    build: (k, color) => {
      const g = k.group();
      // Simple horse body under the rider.
      const horse = 0x6b4a32;
      g.add(k.rot(k.cap(0.22, 0.6, horse, 0, 0.6, 0), 0, 0, Math.PI / 2)); // barrel
      g.add(k.box(0.36, 0.3, 0.18, horse, 0, 0.55, -0.46)); // hindquarters
      g.add(k.rot(k.cyl(0.1, 0.13, 0.4, horse, 0.04, 0.78, 0.4), -0.5, 0, 0)); // neck
      g.add(k.box(0.13, 0.16, 0.26, horse, 0.04, 0.95, 0.56)); // head
      for (const [x, z] of [[-0.16, 0.34], [0.16, 0.34], [-0.16, -0.34], [0.16, -0.34]] as const)
        g.add(k.cyl(0.05, 0.05, 0.6, horse, x, 0.3, z)); // legs
      g.add(k.box(0.5, 0.06, 0.34, C.LEATHER, 0, 0.78, -0.05)); // saddle
      // Knight rider, raised onto the saddle.
      const rider = k.humanoid({ body: C.STEEL, bulk: 1.15, shoulders: true });
      rider.position.set(0, 0.78, -0.05);
      rider.scale.setScalar(0.85);
      rider.add(k.sph(0.14, C.STEEL, 0, 0.92, 0)); // helmet
      rider.add(k.cone(0.05, 0.12, color, 0, 1.06, 0)); // crest
      rider.add(k.cyl(0.018, 0.018, 1.0, C.DARKWOOD, 0.24, 0.5, 0.2)); // lance haft
      rider.add(k.cone(0.04, 0.16, C.STEEL, 0.24, 1.04, 0.2)); // lance tip
      rider.add(shield(k, color, 1.15));
      g.add(rider);
      return g;
    },
  },
];
