// Folk NPC creature minis — townsfolk + playable ancestries, now generated by
// the procedural miniature engine ($lib/minis) via fromRecipe(). The six
// ancestries map straight onto generator species (dwarf/elf/halfling/tiefling/
// dragonborn/half_orc); the civilians reskin the neutral `fighter` class (empty
// marker set) with armorWeight:'none', a relaxed `standing` pose and a palette +
// small prop so a villager reads as a villager, not an adventurer. ModelDef
// metadata is preserved for pickMiniId / the Figures panel / the auto NPC
// catalog.
import type { ModelDef } from './types.ts';
import { fromRecipe } from './miniRecipe.ts';

export const MODELS: ModelDef[] = [
  {
    id: 'commoner', label: 'Commoner', icon: '🧑', color: '#8a6f4a', category: 'NPC', creature: true,
    keywords: ['commoner', 'peasant', 'villager', 'refugee', 'servant', 'beggar', 'civilian'],
    build: fromRecipe({
      name: 'Commoner', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'warm_grey', leather: 'dark_brown' },
    }),
  },
  {
    id: 'farmer', label: 'Farmer', icon: '🧑‍🌾', color: '#c9a227', category: 'NPC', creature: true,
    keywords: ['farmer', 'woodsman', 'stablemaster'],
    build: fromRecipe({
      name: 'Farmer', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['spear', 'feather_cap'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'ochre', cloth2: 'ochre', leather: 'tan_leather' },
    }),
  },
  {
    id: 'merchant', label: 'Merchant', icon: '🧑‍💼', color: '#3b6ea5', category: 'NPC', creature: true,
    keywords: ['merchant', 'trader', 'shopkeeper', 'innkeeper', 'fence'],
    build: fromRecipe({
      name: 'Merchant', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['belt_pouch'], poseFamily: 'standing', armorWeight: 'none',
      classMarkers: ['half_robe'], materials: { cloth: 'arcane_blue', cloth2: 'midnight_blue', metal: 'gold' },
    }),
  },
  {
    id: 'noble', label: 'Noble', icon: '🤴', color: '#b23b3b', category: 'NPC', creature: true,
    keywords: ['noble', 'noblewoman', 'lord', 'aristocrat', 'magistrate', 'judge'],
    build: fromRecipe({
      name: 'Noble', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      classMarkers: ['full_robe'], materials: { cloth: 'wine_red', cloth2: 'royal_purple', metal: 'gold' },
    }),
  },
  {
    id: 'blacksmith', label: 'Blacksmith', icon: '🔨', color: '#5a5f66', category: 'NPC', creature: true,
    keywords: ['blacksmith', 'smith', 'carpenter', 'miner'],
    build: fromRecipe({
      name: 'Blacksmith', class: 'fighter', species: 'human', category: 'npc_mini', bodyType: 'burly',
      gear: ['warhammer'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'dark_brown', leather: 'dark_brown', metal: 'dark_iron' },
    }),
  },
  {
    id: 'scholar', label: 'Scholar', icon: '📖', color: '#3b6ea5', category: 'NPC', creature: true,
    keywords: ['scholar', 'scribe', 'librarian', 'messenger'],
    build: fromRecipe({
      name: 'Scholar', class: 'wizard', species: 'human', category: 'npc_mini',
      gear: ['spellbook'], poseFamily: 'reading_spellbook', armorWeight: 'none',
      classMarkers: ['full_robe'], materials: { cloth: 'arcane_blue', cloth2: 'midnight_blue' },
    }),
  },
  {
    id: 'priest-npc', label: 'Priest', icon: '⛪', color: '#e8e2d0', category: 'NPC', creature: true,
    keywords: ['priest npc', 'acolyte', 'monk npc'],
    build: fromRecipe({
      name: 'Priest', class: 'cleric', species: 'human', category: 'npc_mini',
      gear: ['holy_symbol_necklace'], poseFamily: 'blessing_gesture', armorWeight: 'none',
      classMarkers: ['hood_up', 'full_robe', 'holy_symbol'], materials: { cloth: 'cream_robes', metal: 'gold', magic: 'soft_gold' },
    }),
  },
  {
    id: 'child', label: 'Child', icon: '🧒', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['child', 'kid'],
    build: fromRecipe({
      name: 'Child', class: 'fighter', species: 'halfling', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'forest_green', leather: 'tan_leather' },
    }),
  },
  {
    id: 'elder', label: 'Elder', icon: '👴', color: '#9a9488', category: 'NPC', creature: true,
    keywords: ['elder', 'old man', 'old woman'],
    build: fromRecipe({
      name: 'Elder', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['quarterstaff'], poseFamily: 'standing', armorWeight: 'none',
      speciesMarkers: ['full_beard'], materials: { cloth: 'warm_grey', hair: 'white_hair' },
    }),
  },
  {
    id: 'prisoner', label: 'Prisoner', icon: '⛓', color: '#5a4a38', category: 'NPC', creature: true,
    keywords: ['prisoner', 'captive', 'slave'],
    build: fromRecipe({
      name: 'Prisoner', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['none'], poseFamily: 'shambling', armorWeight: 'none',
      materials: { cloth: 'dark_brown', skin: 'tan_skin' },
    }),
  },
  {
    id: 'hooded-stranger', label: 'Hooded Stranger', icon: '🕵', color: '#2a2a30', category: 'NPC', creature: true,
    keywords: ['hooded stranger', 'shady', 'mysterious figure', 'cloaked'],
    build: fromRecipe({
      name: 'Hooded Stranger', class: 'rogue', species: 'human', category: 'npc_mini',
      gear: ['hooded_cloak'], poseFamily: 'standing', armorWeight: 'light',
      classMarkers: ['hood_up'], materials: { cloth: 'charcoal', cloth2: 'charcoal', leather: 'black_leather' },
    }),
  },
  {
    id: 'fisherman', label: 'Fisherman', icon: '🎣', color: '#3b6ea5', category: 'NPC', creature: true,
    keywords: ['fisherman', 'sailor', 'dockworker', 'hunter'],
    build: fromRecipe({
      name: 'Fisherman', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['quarterstaff', 'feather_cap'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'dusty_teal', cloth2: 'arcane_blue', leather: 'tan_leather' },
    }),
  },
  {
    id: 'guard-npc', label: 'Town Guard', icon: '💂', color: '#9aa3ad', category: 'NPC', creature: true,
    keywords: ['town guard', 'watchman', 'jailer', 'soldier npc'],
    build: fromRecipe({
      name: 'Town Guard', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['spear', 'round_shield'], poseFamily: 'shield_forward', armorWeight: 'medium',
      materials: { metal: 'brushed_steel', cloth: 'charcoal' },
    }),
  },
  {
    id: 'cook', label: 'Cook', icon: '🍳', color: '#e8e2d0', category: 'NPC', creature: true,
    keywords: ['cook', 'tavern server', 'musician'],
    build: fromRecipe({
      name: 'Cook', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['feather_cap'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'cream_robes', cloth2: 'warm_grey', leather: 'tan_leather' },
    }),
  },
  {
    id: 'dwarf-folk', label: 'Dwarf', icon: '🧔', color: '#6e4a2c', category: 'NPC', creature: true,
    keywords: ['dwarf'],
    build: fromRecipe({
      name: 'Dwarf', class: 'fighter', species: 'dwarf', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'dark_brown', leather: 'dark_brown', hair: 'ginger' },
    }),
  },
  {
    id: 'elf-folk', label: 'Elf', icon: '🧝', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['elf'],
    build: fromRecipe({
      name: 'Elf', class: 'fighter', species: 'elf', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      classMarkers: ['half_robe'], materials: { cloth: 'forest_green', hair: 'blonde' },
    }),
  },
  {
    id: 'halfling-folk', label: 'Halfling', icon: '🧑‍🌾', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['halfling', 'gnome', 'smallfolk', 'small adventurer'],
    build: fromRecipe({
      name: 'Halfling', class: 'fighter', species: 'halfling', category: 'npc_mini',
      gear: ['belt_pouch'], poseFamily: 'standing', armorWeight: 'none',
      materials: { cloth: 'ochre', leather: 'dark_brown', hair: 'chestnut' },
    }),
  },
  {
    id: 'tiefling-folk', label: 'Tiefling', icon: '😈', color: '#b23b3b', category: 'NPC', creature: true,
    keywords: ['tiefling'],
    build: fromRecipe({
      name: 'Tiefling', class: 'fighter', species: 'tiefling', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { skin: 'red_skin', cloth: 'wine_red', hair: 'dark_red_hair', bone: 'bone_white' },
    }),
  },
  {
    id: 'dragonborn-folk', label: 'Dragonborn', icon: '🐲', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['dragonborn'],
    build: fromRecipe({
      name: 'Dragonborn', class: 'fighter', species: 'dragonborn', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { scale: 'green_scale', skin: 'green_skin', cloth: 'deep_green' },
    }),
  },
  {
    id: 'half-orc-folk', label: 'Half-Orc', icon: '👹', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['half-orc', 'half orc'],
    build: fromRecipe({
      name: 'Half-Orc', class: 'fighter', species: 'half_orc', category: 'npc_mini',
      gear: ['none'], poseFamily: 'standing', armorWeight: 'none',
      materials: { skin: 'grey_green_skin', cloth: 'dark_brown', bone: 'bone_white' },
    }),
  },
];
