// Procedural CREATURE MINIS: beasts, vermin, and undead. The quadrupeds and
// non-humanoid shapes (wolves, spiders, snakes, swarms, the legless ghost, …)
// are hand-built directly from kit primitives (NOT kit.humanoid) in UNIT space:
// ~1 cell wide/deep, base on y=0, front facing +Z, lower profile than humanoids.
// The bipedal undead (zombie/ghoul/mummy) are now generated by the miniature
// engine via fromRecipe(). Hand-built builders take a ModelKit + per-token tint
// `color`; most fall back to the shared C palette. No 'three' import.
import { C } from './kit.ts';
import type { ModelDef } from './types.ts';
import { fromRecipe, fromBeastRecipe, fromCritterRecipe } from './miniRecipe.ts';

// Every animal in this file is now procedurally generated: quadrupeds
// (wolf/dire-wolf/bear/boar/big-cat/giant-rat/crocodile) via the beast engine
// ($lib/minis/beast.ts); arthropods, the serpent, frog, bat and swarms via the
// critter engine ($lib/minis/critters.ts); and the bipedal undead
// (zombie/ghoul/mummy) via the humanoid engine. Only the legless ghost stays
// hand-built (see docs/miniature-generator.md).
export const MODELS: ModelDef[] = [
  // Gray wolf: low quadruped, pointed snout, upright ears, bushy tail.
  { id: 'wolf', label: 'Wolf', icon: '🐺', color: '#8a8f96', category: 'NPC', creature: true,
    keywords: ['wolf', 'jackal'],
    build: fromBeastRecipe({ name: 'Wolf', beast: 'wolf', stance: 'prowl', materials: { fur: 'grey_fur' } }) },

  // Dire wolf: bigger, darker, shaggier — size 2.
  { id: 'dire-wolf', label: 'Dire Wolf', icon: '🐺', color: '#4a4d54', category: 'NPC', creature: true, size: 2,
    keywords: ['dire wolf', 'worg', 'winter wolf'],
    build: fromBeastRecipe({ name: 'Dire Wolf', beast: 'dire_wolf', stance: 'prowl', materials: { fur: '#4a4d54' } }) },

  // Bear: bulky brown quadruped, round head, tiny ears — size 2.
  { id: 'bear', label: 'Bear', icon: '🐻', color: '#5a4128', category: 'NPC', creature: true, size: 2,
    keywords: ['bear', 'brown bear', 'polar bear'],
    build: fromBeastRecipe({ name: 'Bear', beast: 'bear', materials: { fur: '#5a4128' } }) },

  // Giant rat: low body, big ears, buck teeth, long pink tail.
  { id: 'giant-rat', label: 'Giant Rat', icon: '🐀', color: '#7a6a58', category: 'NPC', creature: true,
    keywords: ['giant rat', 'rat'],
    build: fromBeastRecipe({ name: 'Giant Rat', beast: 'giant_rat', materials: { fur: '#7a6a58' } }) },

  // Giant spider: round abdomen, smaller cephalothorax, 8 angled legs, fangs.
  { id: 'giant-spider', label: 'Giant Spider', icon: '🕷', color: '#2a2630', category: 'NPC', creature: true,
    keywords: ['giant spider', 'spider'],
    build: fromCritterRecipe({ name: 'Giant Spider', critter: 'spider', materials: { scale: '#2a2630' } }) },

  // Giant snake: coiled body via stacked tori, raised head striking forward.
  { id: 'giant-snake', label: 'Giant Snake', icon: '🐍', color: '#4a7340', category: 'NPC', creature: true,
    keywords: ['giant snake', 'serpent', 'python', 'constrictor'],
    build: fromCritterRecipe({ name: 'Giant Snake', critter: 'snake', materials: { scale: '#4a7340' } }) },

  // Giant scorpion: flat segmented body, forward claws, curled stinger tail.
  { id: 'giant-scorpion', label: 'Giant Scorpion', icon: '🦂', color: '#5a4a2c', category: 'NPC', creature: true,
    keywords: ['giant scorpion', 'scorpion'],
    build: fromCritterRecipe({ name: 'Giant Scorpion', critter: 'scorpion', materials: { scale: '#5a4a2c', bone: 'bone_white' } }) },

  // Boar: brown quadruped, snout, tusks, bristly ridge.
  { id: 'boar', label: 'Boar', icon: '🐗', color: '#5a4632', category: 'NPC', creature: true,
    keywords: ['boar', 'warthog', 'pig'],
    build: fromBeastRecipe({ name: 'Boar', beast: 'boar', materials: { fur: '#5a4632' } }) },

  // Big cat: sleek long-bodied quadruped, long tail, small round ears — size 2.
  { id: 'big-cat', label: 'Big Cat', icon: '🐆', color: '#c79a4a', category: 'NPC', creature: true, size: 2,
    keywords: ['lion', 'tiger', 'panther', 'big cat', 'sabretooth'],
    build: fromBeastRecipe({ name: 'Big Cat', beast: 'big_cat', stance: 'prowl', materials: { fur: '#c79a4a' } }) },

  // Giant bat: small body, two big spread wings, hangs/flies low.
  { id: 'giant-bat', label: 'Giant Bat', icon: '🦇', color: '#3a2f3a', category: 'NPC', creature: true,
    keywords: ['giant bat', 'bat'],
    build: fromCritterRecipe({ name: 'Giant Bat', critter: 'bat', materials: { fur: '#4a3f4a' } }) },

  // Giant frog: squat wide body, big folded back legs, wide mouth, bulging eyes.
  { id: 'giant-frog', label: 'Giant Frog', icon: '🐸', color: '#5f8a45', category: 'NPC', creature: true,
    keywords: ['giant frog', 'toad'],
    build: fromCritterRecipe({ name: 'Giant Frog', critter: 'frog', materials: { skin: '#5f8a45' } }) },

  // Crocodile: very long, very low quadruped, toothy snout, ridged back — size 2.
  { id: 'crocodile', label: 'Crocodile', icon: '🐊', color: '#3f5638', category: 'NPC', creature: true, size: 2,
    keywords: ['crocodile', 'alligator', 'croc'],
    build: fromBeastRecipe({ name: 'Crocodile', beast: 'crocodile', materials: { scale: 'green_scale', bone: 'bone_white' } }) },

  // Giant centipede: long row of segments, many tiny legs, antennae.
  { id: 'giant-centipede', label: 'Giant Centipede', icon: '🐛', color: '#7a3a2a', category: 'NPC', creature: true,
    keywords: ['giant centipede', 'centipede'],
    build: fromCritterRecipe({ name: 'Giant Centipede', critter: 'centipede', materials: { scale: '#7a3a2a' } }) },

  // Giant crab: wide squashed shell, two big front claws, legs.
  { id: 'giant-crab', label: 'Giant Crab', icon: '🦀', color: '#b04a3a', category: 'NPC', creature: true,
    keywords: ['giant crab', 'crab'],
    build: fromCritterRecipe({ name: 'Giant Crab', critter: 'crab', materials: { scale: '#b04a3a' } }) },

  // Rat swarm: a cluster of tiny rat blobs spread low over the cell.
  { id: 'rat-swarm', label: 'Rat Swarm', icon: '🐀', color: '#6a5a48', category: 'NPC', creature: true,
    keywords: ['rat swarm', 'swarm of rats'],
    build: fromCritterRecipe({ name: 'Rat Swarm', critter: 'rat_swarm', materials: { fur: '#6a5a48' } }) },

  // Bug swarm: a cloud of tiny dark bodies hovering at varied heights.
  { id: 'bug-swarm', label: 'Insect Swarm', icon: '🦟', color: '#2a2620', category: 'NPC', creature: true,
    keywords: ['insect swarm', 'swarm of insects', 'bug swarm', 'locusts'],
    build: fromCritterRecipe({ name: 'Insect Swarm', critter: 'insect_swarm', materials: { fur: '#6a6658' } }) },

  // Zombie: hunched humanoid, sickly green skin, arms outstretched forward.
  { id: 'zombie', label: 'Zombie', icon: '🧟', color: '#7a8a5a', category: 'NPC', creature: true,
    keywords: ['zombie', 'walking dead'],
    build: fromRecipe({
      name: 'Zombie', class: 'fighter', species: 'human', category: 'monster_mini',
      gear: ['none'], poseFamily: 'shambling', armorWeight: 'none',
      speciesMarkers: ['short_hair'], materials: { skin: 'grey_green_skin', cloth: 'dark_brown', hair: 'dark_red_hair' },
    }) },

  // Ghoul: gaunt slim undead, gray skin, raking claws.
  { id: 'ghoul', label: 'Ghoul', icon: '🧟', color: '#9a9488', category: 'NPC', creature: true,
    keywords: ['ghoul', 'ghast'],
    build: fromRecipe({
      name: 'Ghoul', class: 'rogue', species: 'human', category: 'monster_mini', bodyType: 'gaunt',
      gear: ['none'], poseFamily: 'shambling', armorWeight: 'none',
      speciesMarkers: ['bald', 'slender_build'], classMarkers: [], materials: { skin: '#9aa38a', cloth: 'charcoal', bone: 'bone_white' },
    }) },

  // Ghost: translucent upper body fading into a tapering tail to the ground.
  { id: 'ghost', label: 'Ghost', icon: '👻', color: '#cfd6dd', category: 'NPC', creature: true,
    keywords: ['ghost', 'specter', 'spectre', 'wraith', 'shade', 'phantom'],
    build: (k) => {
      const ghostMat = k.mat(C.FOG, { opacity: 0.45 });
      const g = k.group();
      // tapering tail replacing the legs, rooted to the floor
      g.add(k.cone(0.22, 0.6, ghostMat, 0, 0.3, 0));
      // wispy trailing tendrils
      g.add(k.cone(0.05, 0.3, ghostMat, -0.1, 0.15, 0.02, 6));
      g.add(k.cone(0.05, 0.3, ghostMat, 0.1, 0.15, -0.02, 6));
      // torso + head
      g.add(k.cap(0.15, 0.18, ghostMat, 0, 0.66, 0));
      g.add(k.sph(0.13, ghostMat, 0, 0.92, 0));
      // drifting arms
      const aL = k.cap(0.05, 0.2, ghostMat, -0.2, 0.7, 0.04); aL.rotation.z = 0.4; g.add(aL);
      const aR = k.cap(0.05, 0.2, ghostMat, 0.2, 0.7, 0.04); aR.rotation.z = -0.4; g.add(aR);
      // hollow eyes
      g.add(k.sph(0.025, k.glow(0x9ad0ff, 0.8), -0.05, 0.93, 0.1));
      g.add(k.sph(0.025, k.glow(0x9ad0ff, 0.8), 0.05, 0.93, 0.1));
      // raise off the floor slightly to read as floating
      g.position.y = 0.06;
      return g;
    } },

  // Mummy: bandage-wrapped humanoid, arms outstretched, dangling wraps.
  { id: 'mummy', label: 'Mummy', icon: '🧟', color: '#cabf94', category: 'NPC', creature: true,
    keywords: ['mummy'],
    build: fromRecipe({
      name: 'Mummy', class: 'fighter', species: 'human', category: 'monster_mini',
      gear: ['none'], poseFamily: 'shambling', armorWeight: 'none',
      speciesMarkers: ['bald'], materials: { skin: '#cabf94', cloth: '#d8cca0', cloth2: '#bfb088' },
    }) },
];
