// Arcane / roguish PC creature minis — now generated by the procedural
// miniature engine ($lib/minis) via fromRecipe(). Each ModelDef keeps its stable
// id / label / icon / color / category / keywords and swaps only its `build` for
// a recipe. Elemental mages, the necromancer and the utility casters have no
// dedicated class in the 12-class table, so they reskin the nearest caster
// (wizard / warlock / rogue) with a palette + magic-glow colour — exactly the
// palette-driven variety the engine is built for.
import type { ModelDef } from './types.ts';
import { fromRecipe } from './miniRecipe.ts';

export const MODELS: ModelDef[] = [
  {
    id: 'wizard-staff', label: 'Wizard (Staff)', icon: '🧙', color: '#3b6ea5',
    category: 'PC', creature: true,
    keywords: ['wizard', 'mage', 'sorcerer', 'spellcaster', 'enemy mage'],
    build: fromRecipe({
      name: 'Wizard', class: 'wizard', species: 'human',
      gear: ['wizard_staff', 'spellbook'], poseFamily: 'casting_staff',
      materials: { cloth: 'arcane_blue', cloth2: 'midnight_blue', magic: 'arcane_cyan' },
    }),
  },
  {
    id: 'wizard-book', label: 'Wizard (Book)', icon: '📖', color: '#6ad0ff',
    category: 'PC', creature: true,
    keywords: ['scholar mage', 'conjurer', 'summoner', 'book wizard'],
    build: fromRecipe({
      name: 'Book Wizard', class: 'wizard', species: 'human',
      gear: ['spellbook', 'wand'], poseFamily: 'reading_spellbook',
      classMarkers: ['hood_up', 'full_robe', 'arcane_glow'],
      materials: { cloth: 'arcane_blue', cloth2: 'arcane_blue', magic: 'arcane_cyan' },
    }),
  },
  {
    id: 'warlock', label: 'Warlock', icon: '😈', color: '#4a7340',
    category: 'PC', creature: true,
    keywords: ['warlock', 'enemy warlock', 'occultist'],
    build: fromRecipe({
      name: 'Warlock', class: 'warlock', species: 'human',
      gear: ['eldritch_flame', 'occult_tome'], poseFamily: 'eldritch_cast',
      classMarkers: ['hood_up'], materials: { cloth: 'deep_green', cloth2: 'midnight_blue', magic: 'eldritch_green' },
    }),
  },
  {
    id: 'cleric', label: 'Cleric', icon: '⛪', color: '#d4af37',
    category: 'PC', creature: true,
    keywords: ['cleric', 'priest', 'acolyte', 'healer', 'dark priest'],
    build: fromRecipe({
      name: 'Cleric', class: 'cleric', species: 'human',
      gear: ['mace', 'holy_symbol_necklace'], poseFamily: 'blessing_gesture',
      materials: { cloth: 'cream_robes', metal: 'gold', magic: 'soft_gold' },
    }),
  },
  {
    id: 'druid', label: 'Druid', icon: '🌿', color: '#3f6b3a',
    category: 'PC', creature: true,
    keywords: ['druid', 'enemy druid', 'shaman'],
    build: fromRecipe({
      name: 'Druid', class: 'druid', species: 'human',
      gear: ['nature_staff', 'leaf_charms'], poseFamily: 'spell_hand_extended',
      classMarkers: ['hood_up'], materials: { cloth: 'deep_green', magic: 'nature_green' },
    }),
  },
  {
    id: 'bard', label: 'Bard', icon: '🎵', color: '#b23b3b',
    category: 'PC', creature: true,
    keywords: ['bard', 'performer', 'musician', 'minstrel'],
    build: fromRecipe({
      name: 'Bard', class: 'bard', species: 'human',
      gear: ['lute', 'rapier', 'feather_cap'], poseFamily: 'performance_pose',
      materials: { cloth: 'wine_red', cloth2: 'arcane_blue' },
    }),
  },
  {
    id: 'necromancer', label: 'Necromancer', icon: '💀', color: '#5d5a54',
    category: 'PC', creature: true,
    keywords: ['necromancer', 'undead spellcaster', 'death mage'],
    build: fromRecipe({
      name: 'Necromancer', class: 'wizard', species: 'human',
      gear: ['wizard_staff', 'occult_tome'], poseFamily: 'casting_staff',
      classMarkers: ['hood_up', 'full_robe', 'arcane_glow'],
      materials: { cloth: 'charcoal', cloth2: 'midnight_blue', magic: 'eldritch_green', bone: 'bone_white' },
    }),
  },
  {
    id: 'fire-mage', label: 'Fire Mage', icon: '🔥', color: '#ff7a2a',
    category: 'PC', creature: true,
    keywords: ['fire mage', 'pyromancer'],
    build: fromRecipe({
      name: 'Fire Mage', class: 'wizard', species: 'human',
      gear: ['wizard_staff'], poseFamily: 'casting_staff', classMarkers: ['hood_up', 'full_robe', 'arcane_glow'],
      materials: { cloth: 'flame_orange', cloth2: 'wine_red', magic: 'ember_orange' },
    }),
  },
  {
    id: 'ice-mage', label: 'Ice Mage', icon: '❄️', color: '#bfe3ff',
    category: 'PC', creature: true,
    keywords: ['ice mage', 'frost', 'cryomancer'],
    build: fromRecipe({
      name: 'Ice Mage', class: 'wizard', species: 'human',
      gear: ['wizard_staff'], poseFamily: 'casting_staff', classMarkers: ['hood_up', 'full_robe', 'arcane_glow'],
      materials: { cloth: 'arcane_blue', cloth2: 'midnight_blue', magic: 'storm_blue' },
    }),
  },
  {
    id: 'lightning-mage', label: 'Lightning Mage', icon: '⚡', color: '#ffe066',
    category: 'PC', creature: true,
    keywords: ['lightning mage', 'storm', 'tempest'],
    build: fromRecipe({
      name: 'Lightning Mage', class: 'wizard', species: 'human',
      gear: ['wizard_staff'], poseFamily: 'spell_hand_extended', classMarkers: ['hood_up', 'full_robe', 'arcane_glow'],
      materials: { cloth: 'midnight_blue', cloth2: 'royal_purple', magic: 'storm_blue' },
    }),
  },
  {
    id: 'mystic-oracle', label: 'Mystic Oracle', icon: '🔮', color: '#a78bfa',
    category: 'PC', creature: true,
    keywords: ['mystic', 'oracle', 'seer', 'hierophant'],
    build: fromRecipe({
      name: 'Mystic Oracle', class: 'wizard', species: 'human',
      gear: ['orb'], poseFamily: 'reading_spellbook', classMarkers: ['hood_up', 'full_robe'],
      materials: { cloth: 'royal_purple', cloth2: 'midnight_blue', magic: 'fel_violet', metal: 'gold' },
    }),
  },
  {
    id: 'alchemist', label: 'Alchemist', icon: '⚗️', color: '#7bd23a',
    category: 'PC', creature: true,
    keywords: ['alchemist', 'herbalist', 'doctor'],
    // No alchemist class — a half-robed caster with a belt of pouches + a
    // green potion-glow in hand reads the part.
    build: fromRecipe({
      name: 'Alchemist', class: 'druid', species: 'human', armorWeight: 'light',
      gear: ['belt_pouch', 'utility_belt'], poseFamily: 'spell_hand_extended',
      classMarkers: ['half_robe', 'arcane_glow'], materials: { cloth: 'dusty_teal', leather: 'tan_leather', magic: 'nature_green' },
    }),
  },
  {
    id: 'artificer', label: 'Artificer', icon: '🔧', color: '#b7bdc4',
    category: 'PC', creature: true,
    keywords: ['artificer', 'engineer', 'tinkerer'],
    // No artificer class — a light-armored tinkerer with a utility belt and a
    // glowing gadget (wand) in hand.
    build: fromRecipe({
      name: 'Artificer', class: 'rogue', species: 'human', armorWeight: 'light',
      gear: ['wand', 'utility_belt', 'backpack'], poseFamily: 'ready_stance',
      classMarkers: [], materials: { leather: 'tan_leather', cloth: 'warm_grey', metal: 'bronze', magic: 'arcane_cyan' },
    }),
  },
  {
    id: 'hooded-rogue', label: 'Hooded Rogue', icon: '🥷', color: '#4a3220',
    category: 'PC', creature: true,
    keywords: ['rogue', 'thief', 'scout', 'spy', 'assassin', 'cutthroat', 'masked'],
    build: fromRecipe({
      name: 'Hooded Rogue', class: 'rogue', species: 'human',
      gear: ['dagger', 'hooded_cloak', 'utility_belt'], poseFamily: 'crouching_sneak',
      materials: { cloth: 'charcoal', cloth2: 'dark_brown', leather: 'black_leather' },
    }),
  },
  {
    id: 'dual-dagger-rogue', label: 'Dual-Dagger Rogue', icon: '🗡️', color: '#55585e',
    category: 'PC', creature: true,
    keywords: ['dual dagger', 'dual-dagger', 'assassin', 'twin blades'],
    build: fromRecipe({
      name: 'Dual-Dagger Rogue', class: 'rogue', species: 'human',
      gear: ['dual_daggers', 'hooded_cloak'], poseFamily: 'dagger_lunge',
      materials: { cloth: 'charcoal', cloth2: 'midnight_blue', leather: 'black_leather', metal: 'silver' },
    }),
  },
  {
    id: 'shortbow-rogue', label: 'Shortbow Rogue', icon: '🏹', color: '#4a7340',
    category: 'PC', creature: true,
    keywords: ['shortbow', 'ranger rogue', 'archer rogue'],
    build: fromRecipe({
      name: 'Shortbow Rogue', class: 'rogue', species: 'human',
      gear: ['bow', 'quiver', 'hooded_cloak'], poseFamily: 'bow_drawn',
      classMarkers: ['hood_up', 'wilderness_gear'], materials: { cloth: 'deep_green', cloth2: 'forest_green', leather: 'dark_brown' },
    }),
  },
];
