// Monster-humanoid NPC creature minis (goblinoids, orcs, kobolds, reptilians,
// undead, human foes) — now generated by the procedural miniature engine
// ($lib/minis) via fromRecipe(). Each monster ancestry is a generator species
// (goblin/orc/kobold/hobgoblin/bugbear/gnoll/lizardfolk) reusing the shared
// biped rig with its own proportions + markers; drow and the undead reskin the
// nearest species with a palette. ModelDef metadata is preserved so pickMiniId,
// the Figures panel and the auto NPC catalog keep working.
import type { ModelDef } from './types.ts';
import { fromRecipe } from './miniRecipe.ts';

export const MODELS: ModelDef[] = [
  {
    id: 'bandit', label: 'Bandit', icon: '🗡️', color: '#6e4a2c',
    category: 'NPC', creature: true,
    keywords: ['bandit', 'thug', 'brigand', 'outlaw', 'raider', 'highwayman'],
    build: fromRecipe({
      name: 'Bandit', class: 'rogue', species: 'human', category: 'npc_mini',
      gear: ['scimitar', 'belt_pouch'], poseFamily: 'menacing_advance', armorWeight: 'light',
      classMarkers: [], materials: { cloth: 'warm_grey', leather: 'dark_brown', metal: 'dark_iron' },
    }),
  },
  {
    id: 'cultist', label: 'Cultist', icon: '🕯️', color: '#5d5a54',
    category: 'NPC', creature: true,
    keywords: ['cultist', 'acolyte', 'zealot', 'dark robe', 'fanatic'],
    build: fromRecipe({
      name: 'Cultist', class: 'warlock', species: 'human', category: 'npc_mini',
      gear: ['dagger'], poseFamily: 'eldritch_cast', classMarkers: ['hood_up', 'full_robe'],
      materials: { cloth: 'charcoal', cloth2: 'midnight_blue', magic: 'blood_red' },
    }),
  },
  {
    id: 'goblin', label: 'Goblin', icon: '👺', color: '#4a7340',
    category: 'NPC', creature: true,
    keywords: ['goblin', 'gob'],
    build: fromRecipe({
      name: 'Goblin', class: 'fighter', species: 'goblin', category: 'npc_mini',
      gear: ['scimitar'], poseFamily: 'menacing_advance', armorWeight: 'light',
      materials: { skin: 'green_skin', leather: 'dark_brown', metal: 'dark_iron' },
    }),
  },
  {
    id: 'goblin-archer', label: 'Goblin Archer', icon: '🏹', color: '#5a7248',
    category: 'NPC', creature: true,
    keywords: ['goblin archer', 'goblin bow', 'goblin sniper'],
    build: fromRecipe({
      name: 'Goblin Archer', class: 'ranger', species: 'goblin', category: 'npc_mini',
      gear: ['bow', 'quiver'], poseFamily: 'bow_drawn', armorWeight: 'light',
      materials: { skin: 'green_skin', leather: 'dark_brown' },
    }),
  },
  {
    id: 'goblin-boss', label: 'Goblin Boss', icon: '👺', color: '#6e8a3a',
    category: 'NPC', creature: true,
    keywords: ['goblin boss', 'hobgoblin chief', 'goblin king', 'goblin captain'],
    build: fromRecipe({
      name: 'Goblin Boss', class: 'fighter', species: 'goblin', category: 'npc_mini',
      gear: ['sword', 'heater_shield'], poseFamily: 'shield_bash', armorWeight: 'heavy',
      materials: { skin: 'green_skin', metal: 'dark_iron', metal2: 'gold' },
    }),
  },
  {
    id: 'kobold', label: 'Kobold', icon: '🦎', color: '#b23b3b',
    category: 'NPC', creature: true,
    keywords: ['kobold', 'lizard imp'],
    build: fromRecipe({
      name: 'Kobold', class: 'fighter', species: 'kobold', category: 'npc_mini',
      gear: ['spear'], poseFamily: 'menacing_advance', armorWeight: 'none',
      materials: { skin: 'red_skin', scale: 'red_scale', bone: 'bone_white' },
    }),
  },
  {
    id: 'winged-kobold', label: 'Winged Kobold', icon: '🐲', color: '#8a8378',
    category: 'NPC', creature: true,
    keywords: ['winged kobold', 'urd', 'kobold flyer'],
    build: fromRecipe({
      name: 'Winged Kobold', class: 'fighter', species: 'kobold', category: 'npc_mini',
      gear: ['spear', 'wings'], poseFamily: 'sword_lunge', armorWeight: 'none',
      materials: { skin: 'grey_green_skin', scale: 'grey_green_skin', cloth2: 'warm_grey' },
    }),
  },
  {
    id: 'orc', label: 'Orc', icon: '👹', color: '#4a7340',
    category: 'NPC', creature: true,
    keywords: ['orc', 'orruk'],
    build: fromRecipe({
      name: 'Orc', class: 'fighter', species: 'orc', category: 'npc_mini',
      gear: ['battleaxe'], poseFamily: 'menacing_advance', armorWeight: 'medium',
      materials: { skin: 'green_skin', leather: 'dark_brown', metal: 'dark_iron' },
    }),
  },
  {
    id: 'orc-berserker', label: 'Orc Berserker', icon: '🪓', color: '#5f8a45',
    category: 'NPC', creature: true,
    keywords: ['orc berserker', 'orc raider', 'orc reaver'],
    build: fromRecipe({
      name: 'Orc Berserker', class: 'barbarian', species: 'orc', category: 'npc_mini',
      gear: ['dual_axes', 'fur_mantle'], poseFamily: 'axe_roar', armorWeight: 'none',
      materials: { skin: 'green_skin', fur: 'brown_fur', leather: 'red_leather' },
    }),
  },
  {
    id: 'orc-shaman', label: 'Orc Shaman', icon: '🔮', color: '#7d9455',
    category: 'NPC', creature: true,
    keywords: ['orc shaman', 'goblin shaman', 'orc witch doctor'],
    build: fromRecipe({
      name: 'Orc Shaman', class: 'druid', species: 'orc', category: 'npc_mini',
      gear: ['nature_staff', 'leaf_charms'], poseFamily: 'wild_surge',
      classMarkers: ['hood_up', 'nature_motif'], materials: { skin: 'green_skin', cloth: 'deep_green', magic: 'nature_green', bone: 'bone_white' },
    }),
  },
  {
    id: 'hobgoblin', label: 'Hobgoblin', icon: '👹', color: '#c07a3a',
    category: 'NPC', creature: true,
    keywords: ['hobgoblin', 'hob'],
    build: fromRecipe({
      name: 'Hobgoblin', class: 'fighter', species: 'hobgoblin', category: 'npc_mini',
      gear: ['sword', 'heater_shield'], poseFamily: 'shield_bash', armorWeight: 'medium',
      materials: { skin: '#c07a3a', metal: 'blackened_steel', cloth2: 'wine_red' },
    }),
  },
  {
    id: 'bugbear', label: 'Bugbear', icon: '🐻', color: '#7a6a4a',
    category: 'NPC', creature: true,
    keywords: ['bugbear'],
    build: fromRecipe({
      name: 'Bugbear', class: 'barbarian', species: 'bugbear', category: 'npc_mini',
      gear: ['morningstar'], poseFamily: 'menacing_advance', armorWeight: 'light',
      materials: { skin: 'grey_green_skin', fur: 'grey_fur', leather: 'dark_brown' },
    }),
  },
  {
    id: 'gnoll', label: 'Gnoll', icon: '🐺', color: '#a8823a',
    category: 'NPC', creature: true,
    keywords: ['gnoll', 'hyena folk', 'hyena-folk'],
    build: fromRecipe({
      name: 'Gnoll', class: 'fighter', species: 'gnoll', category: 'npc_mini',
      gear: ['spear'], poseFamily: 'menacing_advance', armorWeight: 'light',
      materials: { skin: '#b89050', fur: '#8a6a38', leather: 'dark_brown', bone: 'bone_white' },
    }),
  },
  {
    id: 'lizardfolk', label: 'Lizardfolk', icon: '🦎', color: '#4a7340',
    category: 'NPC', creature: true,
    keywords: ['lizardfolk', 'lizardman', 'reptilian', 'saurian'],
    build: fromRecipe({
      name: 'Lizardfolk', class: 'fighter', species: 'lizardfolk', category: 'npc_mini',
      gear: ['spear'], poseFamily: 'sword_lunge', armorWeight: 'none',
      materials: { scale: 'green_scale', skin: 'green_skin', bone: 'bone_white' },
    }),
  },
  {
    id: 'drow', label: 'Drow', icon: '🧝', color: '#5d5a54',
    category: 'NPC', creature: true,
    keywords: ['drow', 'dark elf'],
    build: fromRecipe({
      name: 'Drow', class: 'rogue', species: 'elf', category: 'npc_mini',
      gear: ['dual_swords', 'hooded_cloak'], poseFamily: 'dagger_lunge', armorWeight: 'light',
      materials: { skin: '#5a4f62', hair: 'white_hair', cloth: 'royal_purple', metal: 'silver' },
    }),
  },
  {
    id: 'skeleton', label: 'Skeleton', icon: '💀', color: '#e8e2d0',
    category: 'NPC', creature: true,
    keywords: ['skeleton', 'skeletal', 'bones'],
    build: fromRecipe({
      name: 'Skeleton', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['sword'], poseFamily: 'shambling', armorWeight: 'none',
      classMarkers: ['skeletal'], speciesMarkers: ['bald'], materials: { bone: 'bone_white', metal: 'dark_iron' },
    }),
  },
  {
    id: 'skeleton-archer', label: 'Skeleton Archer', icon: '🏹', color: '#e8e2d0',
    category: 'NPC', creature: true,
    keywords: ['skeleton archer', 'skeletal archer'],
    build: fromRecipe({
      name: 'Skeleton Archer', class: 'ranger', species: 'human', category: 'npc_mini',
      gear: ['bow', 'quiver'], poseFamily: 'bow_drawn', armorWeight: 'none',
      classMarkers: ['skeletal'], speciesMarkers: ['bald'], materials: { bone: 'bone_white' },
    }),
  },
  {
    id: 'skeleton-warrior', label: 'Skeleton Warrior', icon: '💀', color: '#b7bdc4',
    category: 'NPC', creature: true,
    keywords: ['skeleton warrior', 'armored skeleton', 'death knight'],
    build: fromRecipe({
      name: 'Skeleton Warrior', class: 'fighter', species: 'human', category: 'npc_mini',
      gear: ['sword', 'heater_shield'], poseFamily: 'shield_bash', armorWeight: 'heavy',
      classMarkers: ['skeletal'], speciesMarkers: ['bald'], materials: { bone: 'bone_white', metal: 'blackened_steel', magic: 'blood_red' },
    }),
  },
  {
    id: 'gladiator', label: 'Gladiator', icon: '🛡️', color: '#c98d5e',
    category: 'NPC', creature: true,
    keywords: ['gladiator', 'pit fighter'],
    build: fromRecipe({
      name: 'Gladiator', class: 'barbarian', species: 'human', category: 'npc_mini',
      gear: ['sword', 'heater_shield'], poseFamily: 'shield_bash', armorWeight: 'light',
      classMarkers: [], materials: { skin: 'tan_skin', metal: 'bronze', leather: 'tan_leather' },
    }),
  },
];
