// Procedural CREATURE MINIS: large monsters, dragons, elementals, constructs,
// oozes and plant/special foes. The big humanoid brutes (ogre/troll/giant/
// minotaur/werewolf) are now generated by the miniature engine via fromRecipe()
// (large biped species); the non-humanoid ones (dragons, elementals, oozes,
// constructs, plants, objects) are still hand-built directly from primitives.
// Hand-built builders take a ModelKit + per-token tint `color`; no 'three'
// import. Models build in UNIT space (~1 cell, base on y=0, front +Z); Scene3D
// scales by the token's `size`.
import { C } from './kit.ts';
import type { ModelDef } from './types.ts';
import { fromRecipe, fromBeastRecipe, fromConstructRecipe, fromAmorphousRecipe } from './miniRecipe.ts';

// Big humanoid brutes → humanoid engine (large biped species); dragons →
// quadruped beast engine; humanoid-form constructs (golem, earth-elemental,
// treant, animated-armor, scarecrow, myconid) → construct engine
// ($lib/minis/constructs.ts). Only the amorphous monsters (fire/water/air
// elementals, oozes, flying-sword, shambling-mound, owlbear) stay hand-built —
// no engine yet (docs/miniature-generator.md).
export const MODELS: ModelDef[] = [
  // Lumbering ogre: huge dull-skinned brute with an undersized head and a
  // tree-trunk club resting on its shoulder.
  { id: 'ogre', label: 'Ogre', icon: '👹', color: '#9a8a6a', category: 'NPC', creature: true, size: 2,
    keywords: ['ogre'],
    build: fromRecipe({
      name: 'Ogre', class: 'barbarian', species: 'ogre', category: 'monster_mini',
      gear: ['greatclub'], poseFamily: 'menacing_advance', armorWeight: 'none',
      classMarkers: [], materials: { skin: '#9a8a6a', leather: 'dark_brown', cloth: 'dark_brown' },
    }) },

  // Hunched troll: rangy green frame, overlong arms dragging knuckles, raking
  // claws and a stooped back.
  { id: 'troll', label: 'Troll', icon: '🧌', color: '#6f8f5a', category: 'NPC', creature: true, size: 2,
    keywords: ['troll'],
    build: fromRecipe({
      name: 'Troll', class: 'barbarian', species: 'troll', category: 'monster_mini',
      gear: ['none'], poseFamily: 'pounce', armorWeight: 'none',
      classMarkers: [], materials: { skin: 'green_skin', cloth: 'deep_green', bone: 'bone_white' },
    }) },

  // Minotaur: brawny fur-covered bull-man with a horned snout and a heavy
  // double-bladed axe.
  { id: 'minotaur', label: 'Minotaur', icon: '🐂', color: '#6b4a2c', category: 'NPC', creature: true, size: 2,
    keywords: ['minotaur', 'bull man'],
    build: fromRecipe({
      name: 'Minotaur', class: 'barbarian', species: 'minotaur', category: 'monster_mini',
      gear: ['great_axe'], poseFamily: 'axe_roar', armorWeight: 'none',
      classMarkers: [], materials: { skin: '#6b4a2c', fur: '#5a3f28', bone: 'bone_white', metal: 'dark_iron' },
    }) },

  // Towering giant: crude furs lashed over a massive frame, fists or a rough
  // club, simple stony face.
  { id: 'giant', label: 'Giant', icon: '🗿', color: '#8a8478', category: 'NPC', creature: true, size: 2,
    keywords: ['giant', 'hill giant', 'frost giant', 'ettin'],
    build: fromRecipe({
      name: 'Giant', class: 'barbarian', species: 'giant', category: 'monster_mini',
      gear: ['greatclub', 'fur_mantle'], poseFamily: 'menacing_advance', armorWeight: 'none',
      classMarkers: [], materials: { skin: '#b6a890', fur: 'grey_fur', leather: 'dark_brown', hair: 'brown_hair' },
    }) },

  // Owlbear: bear bulk fused with an owl — hooked beak, feathered ruff and
  // tufted ears, reared up on heavy forelimbs.
  { id: 'owlbear', label: 'Owlbear', icon: '🦉', color: '#7a5a38', category: 'NPC', creature: true, size: 2,
    keywords: ['owlbear'],
    build: (k) => {
      const fur = 0x7a5a38, feather = 0x9a7a4a;
      const g = k.group();
      g.add(k.cap(0.3, 0.32, fur, 0, 0.46, -0.02));          // bulky body
      g.add(k.box(0.5, 0.12, 0.3, fur, 0, 0.36, 0));         // shoulders
      // Hind legs and rearing forelimbs.
      g.add(k.cap(0.1, 0.16, fur, -0.18, 0.16, -0.08));
      g.add(k.cap(0.1, 0.16, fur, 0.18, 0.16, -0.08));
      g.add(k.rot(k.cap(0.09, 0.3, fur, -0.24, 0.42, 0.14), 0.5, 0, 0));
      g.add(k.rot(k.cap(0.09, 0.3, fur, 0.24, 0.42, 0.14), 0.5, 0, 0));
      // Owl head: feathered ruff, round skull, hooked beak, ear tufts.
      g.add(k.sph(0.24, feather, 0, 0.72, 0.06));
      g.add(k.sph(0.18, feather, 0, 0.82, 0.12));
      g.add(k.cone(0.05, 0.12, C.GOLD, 0, 0.8, 0.26, 6));
      g.add(k.sph(0.045, C.GOLD, -0.07, 0.88, 0.22));
      g.add(k.sph(0.045, C.GOLD, 0.07, 0.88, 0.22));
      g.add(k.cone(0.04, 0.12, feather, -0.12, 0.98, 0.04, 6));
      g.add(k.cone(0.04, 0.12, feather, 0.12, 0.98, 0.04, 6));
      return g;
    } },

  // Werewolf: hunched gray-furred lycanthrope with a long snout, pricked ears
  // and outstretched claws.
  { id: 'werewolf', label: 'Werewolf', icon: '🐺', color: '#7a7a7e', category: 'NPC', creature: true, size: 2,
    keywords: ['werewolf', 'lycanthrope', 'wolf man'],
    build: fromRecipe({
      name: 'Werewolf', class: 'barbarian', species: 'werewolf', category: 'monster_mini',
      gear: ['none'], poseFamily: 'pounce', armorWeight: 'none',
      classMarkers: [], materials: { skin: '#7a7a7e', fur: 'grey_fur', bone: 'bone_white' },
    }) },

  // Drake / young dragon: low four-legged body, long neck and head reaching
  // forward, folded wings and a trailing tail.
  { id: 'small-dragon', label: 'Drake', icon: '🐉', color: '#b23b3b', category: 'NPC', creature: true, size: 2,
    keywords: ['drake', 'young dragon', 'wyrmling', 'pseudodragon'],
    build: fromBeastRecipe({ name: 'Drake', beast: 'drake', materials: { scale: '#b23b3b', bone: 'bone_white' } }) },

  // Wyvern: two clawed legs, a long neck, vast spread wings and a barbed
  // stinger-tipped tail arched overhead.
  { id: 'wyvern', label: 'Wyvern', icon: '🐲', color: '#5a6b4a', category: 'NPC', creature: true, size: 2,
    keywords: ['wyvern'],
    build: fromBeastRecipe({ name: 'Wyvern', beast: 'wyvern', materials: { scale: '#5a6b4a', bone: 'bone_white' } }) },

  // Ancient dragon: a serpentine wyrm with a raised horned head, four legs,
  // a long lashing tail and enormous outstretched wings.
  { id: 'dragon-large', label: 'Great Dragon', icon: '🐉', color: '#a02020', category: 'NPC', creature: true, size: 3,
    keywords: ['dragon', 'red dragon', 'ancient dragon', 'wyrm'],
    build: fromBeastRecipe({ name: 'Great Dragon', beast: 'great_dragon', materials: { scale: '#a02020', bone: 'bone_white' } }) },

  // Fire elemental: a rising, twisting tower of flame tapering to a point near
  // the ground — stacked emissive cones in fire/ember/lava hues.
  { id: 'fire-elemental', label: 'Fire Elemental', icon: '🔥', color: '#ff7a2a', category: 'NPC', creature: true, size: 2,
    keywords: ['fire elemental', 'flame elemental', 'magma'],
    build: fromAmorphousRecipe({ name: 'Fire Elemental', amorphous: 'fire_elemental' }) },

  // Water elemental: a churning translucent column of water, swirled with
  // stacked rings and rolling droplets.
  { id: 'water-elemental', label: 'Water Elemental', icon: '🌊', color: '#3b6ea5', category: 'NPC', creature: true, size: 2,
    keywords: ['water elemental', 'ice elemental'],
    build: fromAmorphousRecipe({ name: 'Water Elemental', amorphous: 'water_elemental' }) },

  // Earth elemental: a hulking craggy humanoid heaped from chunky stone boxes
  // and boulders.
  { id: 'earth-elemental', label: 'Earth Elemental', icon: '🪨', color: '#8a8478', category: 'NPC', creature: true, size: 2,
    keywords: ['earth elemental', 'rock elemental', 'stone golem'],
    build: fromConstructRecipe({ name: 'Earth Elemental', construct: 'earth_elemental', materials: { stone: '#8a8478', magic: '#a6e07a' } }) },

  // Air elemental: a faint rising spiral of pale wind — barely-there twisted
  // rings and wisps.
  { id: 'air-elemental', label: 'Air Elemental', icon: '🌀', color: '#cfd6dd', category: 'NPC', creature: true, size: 2,
    keywords: ['air elemental', 'wind', 'storm elemental'],
    build: fromAmorphousRecipe({ name: 'Air Elemental', amorphous: 'air_elemental' }) },

  // Gelatinous cube: a near-clear acid cube creeping forward, a few bones and
  // coins suspended motionless inside.
  { id: 'gelatinous-cube', label: 'Gelatinous Cube', icon: '🟩', color: '#7bd23a', category: 'NPC', creature: true, size: 2,
    keywords: ['gelatinous cube', 'ooze cube'],
    build: fromAmorphousRecipe({ name: 'Gelatinous Cube', amorphous: 'gelatinous_cube', materials: { bone: '#e8e2d0' } }) },

  // Black pudding: a low, melted blob of dark ooze, glistening and amorphous.
  { id: 'black-pudding', label: 'Black Pudding', icon: '⚫', color: '#2a2a2e', category: 'NPC', creature: true, size: 2,
    keywords: ['black pudding', 'ooze', 'slime', 'gray ooze'],
    build: fromAmorphousRecipe({ name: 'Black Pudding', amorphous: 'black_pudding' }) },

  // Golem: a blocky stone construct with slab limbs and faintly glowing rune
  // eyes.
  { id: 'golem', label: 'Golem', icon: '🗿', color: '#9a948a', category: 'NPC', creature: true, size: 2,
    keywords: ['golem', 'clay golem', 'iron golem', 'flesh golem', 'construct'],
    build: fromConstructRecipe({ name: 'Golem', construct: 'golem', materials: { stone: '#9a948a', magic: '#a78bfa' } }) },

  // Animated armor: an empty suit of plate that stands and fights on its own —
  // a gap of darkness at the open neck, ghostly light in the helm.
  { id: 'animated-armor', label: 'Animated Armor', icon: '🛡', color: '#b7bdc4', category: 'NPC', creature: true, size: 1,
    keywords: ['animated armor', 'living armor', 'empty suit'],
    build: fromConstructRecipe({ name: 'Animated Armor', construct: 'animated_armor', materials: { metal: '#b7bdc4', magic: '#6ad0ff' } }) },

  // Flying sword: a lone blade hovering point-down, slowly turning in the air,
  // wreathed in a faint arcane glimmer.
  { id: 'flying-sword', label: 'Flying Sword', icon: '🗡', color: '#c8ccd2', category: 'NPC', creature: true, size: 1,
    keywords: ['flying sword', 'animated sword', 'dancing blade'],
    build: fromAmorphousRecipe({ name: 'Flying Sword', amorphous: 'flying_sword', materials: { metal: '#c8ccd2', metal2: 'gold', magic: 'arcane_cyan' } }) },

  // Treant: an ancient tree roused to walk — thick bark trunk, root legs,
  // branch arms and a leafy crown with a hint of a face.
  { id: 'treant', label: 'Treant', icon: '🌳', color: '#5a4128', category: 'NPC', creature: true, size: 2,
    keywords: ['treant', 'awakened tree', 'tree creature'],
    build: fromConstructRecipe({ name: 'Treant', construct: 'treant', materials: { wood: '#5a4128', magic: 'nature_green' } }) },

  // Shambling mound: a hunched heap of rotting vines, leaves and muck with no
  // clear head — just a tangled, looming mass.
  { id: 'shambling-mound', label: 'Shambling Mound', icon: '🌿', color: '#3f6b3a', category: 'NPC', creature: true, size: 2,
    keywords: ['shambling mound', 'vine horror', 'plant monster'],
    build: fromAmorphousRecipe({ name: 'Shambling Mound', amorphous: 'shambling_mound', materials: { leather: '#5a4a2e' } }) },

  // Myconid: a fungus-folk with a pale stalk body, stubby arms and a broad
  // rounded cap.
  { id: 'myconid', label: 'Myconid', icon: '🍄', color: '#cabf94', category: 'NPC', creature: true, size: 1,
    keywords: ['myconid', 'mushroom folk', 'fungus'],
    build: fromConstructRecipe({ name: 'Myconid', construct: 'myconid', materials: { bone: '#cabf94' } }) },

  // Scarecrow: a straw-stuffed figure lashed to a cross-post, burlap head and
  // bundled straw hands.
  { id: 'animated-scarecrow', label: 'Scarecrow', icon: '🎃', color: '#cabf94', category: 'NPC', creature: true, size: 1,
    keywords: ['scarecrow', 'straw man'],
    build: fromConstructRecipe({ name: 'Scarecrow', construct: 'scarecrow', materials: { cloth: '#cabf94', wood: '#6f4f30' } }) },
];
